"""
TriSeva Global Multi-Agent State Definition.

Defines the centralized TypedDict state object used by LangGraph to pass data across nodes,
including query routing, multimodal OCR text, domain agent generations, NLI critic scores,
translation metadata, and telemetry metrics.
"""

from typing import TypedDict, Optional, List, Annotated
from langgraph.graph.message import add_messages


class TriSevaState(TypedDict):
    """Centralized State Schema for the TriSeva Multi-Agent Graph.

    Attributes:
        user_query (str): English-translated or raw query submitted by the user.
        session_id (str): Unique tracking identifier for conversation session memory.
        image_path (Optional[str]): Absolute file path to an uploaded document image.
        domain (Optional[str]): Classified target domain ('health', 'legal', 'agriculture').
        domain_confidence (Optional[float]): Router classification confidence score (0.0 to 1.0).
        retrieved_chunks (Optional[List[str]]): Top-k context passages retrieved from RAG ChromaDB.
        sources (Optional[List[dict]]): Source metadata list containing document names and scores.
        image_text (Optional[str]): Extracted text transcribed from document image via OCR/VLM.
        draft_answer (Optional[str]): Initial response draft generated by domain specialist agent.
        final_answer (Optional[str]): Approved answer after NLI critic validation and back-translation.
        faithfulness_score (Optional[float]): NLI Groundedness score (0.0 to 1.0) assigned by Critic.
        relevancy_score (Optional[float]): Query-relevance score (0.0 to 1.0) assigned by Critic.
        retry_count (int): Counter tracking iteration loops through the ReAct agent graph (max 2).
        chat_history (Annotated[list, add_messages]): LangGraph appended conversation turn list.
        quiz (Optional[List[dict]]): Optional comprehension quiz questions for citizen engagement.
        domain_disclaimer (Optional[str]): Domain safety disclaimer text (e.g. medical/legal advice note).
        domain_override (Optional[str]): Optional user domain selection overriding automatic routing.
        telemetry (Optional[dict]): System telemetry metrics dictionary tracking hops, latency, and fallbacks.
        critic_feedback (Optional[str]): Feedback reason provided by Critic if draft requires refinement.
        original_language (Optional[str]): BCP-47 language tag of original input (e.g. 'hi-IN', 'en-IN').
        original_query (Optional[str]): Verbatim query text as originally entered by the citizen.
        script_hint (Optional[str]): Script classification tag ('devanagari' or 'latin' Hinglish).
    """

    # ── User Input & Session Metadata ─────────────────────────────────────
    user_query: str                        # Current working query (English translated if applicable)
    session_id: str                        # Unique session identifier for memory persistence
    image_path: Optional[str]              # Path to uploaded document image (prescription, land record)

    # ── Domain Classification & Routing ───────────────────────────────────
    domain: Optional[str]                  # Target domain: 'health' | 'legal' | 'agriculture'
    domain_confidence: Optional[float]     # Router confidence score

    # ── Multimodal OCR & Context Retrieval ────────────────────────────────
    retrieved_chunks: Optional[List[str]]  # Top-k retrieved passages from vector database
    sources: Optional[List[dict]]          # Chunk metadata dictionaries ({source, score})
    image_text: Optional[str]              # Extracted OCR/VLM document text

    # ── Agent Generation & Refinement ────────────────────────────────────
    draft_answer: Optional[str]            # Initial answer from domain specialist agent
    final_answer: Optional[str]            # Approved final answer after critic validation

    # ── NLI Critic Evaluation ─────────────────────────────────────────────
    faithfulness_score: Optional[float]    # Groundedness score (0.0 to 1.0)
    relevancy_score: Optional[float]       # Query relevance score (0.0 to 1.0)
    retry_count: int                       # Current retry loop iteration count

    # ── LangGraph Conversation Memory ──────────────────────────────────────
    chat_history: Annotated[list, add_messages]  # Appended message history

    # ── Interactive Engagement & Telemetry ─────────────────────────────────
    quiz: Optional[List[dict]]             # Generated comprehension quiz questions
    domain_disclaimer: Optional[str]       # Safety disclaimer text based on classified domain
    domain_override: Optional[str]         # User domain override choice
    telemetry: Optional[dict]              # Performance metrics (routing hops, latency, fallbacks)
    critic_feedback: Optional[str]         # Refinement feedback from critic on rejection
    original_language: Optional[str]       # Detected BCP-47 language code
    original_query: Optional[str]          # Raw user query before translation
    script_hint: Optional[str]             # Script hint: 'devanagari' vs 'latin' Hinglish